config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :items
  resources :customers
  resources :cart
  resources :order
  post '/cart/clearall', to: 'cart#deleteallItems'
  post '/cart/showitems', to: 'cart#showCart'
  post '/cart/deletefromcart', to: 'cart#deleteFromCart'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    puts "In show method"
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
      if @product.save
        redirect_to products_path
      else
        render :new
      end
  end

  def edit
      @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to products_path
      else
        render :edit
      end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:title, :description)
    end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
<div>
  <%= f.submit %>
</div>
<% end %>

app/views/products/index.html.erb
<h1>Products list</h1>
<%= link_to "Create", new_product_path %>
<table>
  <thead>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
  </thead>
  <% @products.each do |product| %>
  <tr>
    <td><%= product.title %></td>
    <td><%= product.description %></td>
    <td>
      <%= link_to "Edit", edit_product_path(product) %>
      <%= link_to "Delete", product, method: :delete, data: { confirm: "Are you sure you want to delete this product?"} %>
      <%= link_to "Show", product_path(product) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div>
  <%= f.submit %>
</div>
<% end %>

app/views/products/show.html.erb
<table>
  <thead>
    <th>Title</th>
    <th>Description</th>
  </thead>
  <tr>
    <td><%= @product.title %></td>
    <td><%= @product.description %></td>
  </tr>
  </table>  
    <%= link_to "Index", products_path %>
  